### PR TITLE
Conscience language

### PR DESCRIPTION
**Pull request by ge0ffrey**
I missed these the first time going through the files.

### CODE REVIEW

**Comment by dupliaka** [comment]
Shell we leave this file?
http://github.com/kiegroup/optaplanner-website/blob/14c1fe22c7552a0a5d32f53f26d12a01f45cf2fe/optaplanner-website-root/assets/learn/slides/optaplanner-presentation/website/reveal/js/reveal.js#L1282-L1282

**Comment by ge0ffrey** [comment]
@dupliaka Yes, its an "included" javascript file of reveal.js. We shouldn't modify included files in any way.
We should maybe think about upgrading the reveal.js version and hope their newer files don't have this issue.

**Comment by ge0ffrey** [comment]
Would you mind reviewing this PR (accepted/comments/request changes)?

**Comment by dupliaka** [comment]
Ok, BTW I have checked - the latest versions don't have this issue LGTM

**Review by dupliaka — APPROVED** [review]

**Comment by ge0ffrey** [comment]
Thanks Anna, good to know!
Upgrading reveal.js has been non-trivial in the past, due BC breaking changes, but we should probably just try it out and go through the slides to see they are impacted. Anyway, that's a different issue/PR than this one.

**Pull request merged**
