### PR TITLE
Updated jbake-core to v2.7.0-rc.3

### PR DESCRIPTION
**Pull request by jonbullock**
Includes fix for: https://github.com/jbake-org/jbake/issues/708

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Thanks Jon!

**Review by ge0ffrey — APPROVED** [review]

**Comment by ge0ffrey** [comment]
@jonbullock 

```
<#if content.nextContent??>
```
always returns false now in this code:
  https://github.com/kiegroup/optaplanner-website/blob/master/templates/post.ftl#L61

So all the blog post's next links are now disabled:

image

**Comment by jonbullock** [comment]
Ah, I'll take a look.

**Comment by jonbullock** [comment]
jbake-core v2.7.0-rc.4 is available which fixes the next issue.

**Comment by yurloc** [comment]
Thanks Jon, I've opened #382.

**Pull request merged**
